### ISSUE TITLE
Add spec types to all functions

### ISSUE THREAD

**Issue by yordis** [robinmonjo/coincoin#14]
@robinmonjo  before you keep going man it is really important to add the type spec of the functions. You dont need to write that much documentation but at least with the type spec I know what the function specs and what it returns.

I wish I could do it myself but I have to track down all the code in each function to know about it.

**Comment by robinmonjo** [comment]
This is a work in progress. It takes some times, dialyzer drive me nuts !! Not that easy to get specs right ...
