### ISSUE TITLE
Nonce typo

### ISSUE THREAD

**Issue by dmlittle** [robinmonjo/coincoin#24]
`nounce` should be spelled `nonce`. Unfortunately it's not only in the documentation but also in the code base as part of the `Blockchain.Difficulty` and `Blockchain.Block` structs. I can put a PR renaming it but wanted to open an issue first.

**Comment by robinmonjo** [comment]
Wahou thank you very much for the issue ! This is embarrassing, I could have lived all my life thinking it's a "nounce" 😂.

Fixed it 😊
